stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: php:7.4-cli
  script:
    - composer install
    - vendor/bin/phpunit

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag my-app $CI_REGISTRY/my-app:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY/my-app:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
    - kubectl apply -f k8s/deployment.yaml
